# Generated by Django 5.2.17 on 2026-09-20 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def initialize_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserState = apps.get_model('assistant', 'UserState')
    alias = schema_editor.connection.alias
    batch = []
    for user_id in User.objects.using(alias).values_list('pk', flat=True).iterator(chunk_size=500):
        batch.append(UserState(user_id=user_id, has_seen_dashboard=True))
        if len(batch) == 500:
            UserState.objects.using(alias).bulk_create(batch)
            batch = []
    UserState.objects.using(alias).bulk_create(batch)
    # These accounts could never access the authenticated dashboard.
    pending = User.objects.using(alias).filter(
        is_active=False, groups__name='CareerPilot email verification pending')
    UserState.objects.using(alias).filter(user_id__in=pending.values('pk')).update(has_seen_dashboard=False)


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_seen_dashboard', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(initialize_existing_users, migrations.RunPython.noop),
    ]
